### PR TITLE
Feature fundingfact mv

### PR DESCRIPTION
**Pull request by michael1visser**
Issue #32 Ready for review :awaiting_review

### CODE REVIEW

**Comment by clarknoah** [comment]
@michael1visser Your branch has a merge conflict with develop, resolve this and then I can review it

**Comment by michael1visser** [comment]
Fixed merge conflict in index.css

**Comment by clarknoah** [comment]
@michael1visser this looks really good, a couple things: 
1. Update you classes per what I mentioned in the Slack channel (`<ComponentName>-<class-identifier>`. So the class `img-right` would be `FundingFact-img-right`)
2, Your `p` class is wayyyy to generic, update that too
3. Have the image position be determined by a prop called `img-position` and have it take a value of `left` or `right`. This is so that position is more explicitly defined. You can also have it default to img left like you originally had it if a value isn't declared.

**Comment by michael1visser** [comment]
Updated classes to all include FundingFact and changed imgRight to imgPositionRight to be a little more explicit.

**Comment by clarknoah** [comment]
Good stuff!

**Pull request merged**
