### PR TITLE
ContactUsPage update

### PR DESCRIPTION
**Pull request by hemao**

### CODE REVIEW

**Comment by allison-johnson** [comment]
@hemao , looks good! Just a couple of quick fixes before I merge your PR:
- There is too much space between the form and the text box below it ("For any..."). 
- All of text on the buttons should be capitalized, as per the mock up.

Let me know when you've pushed up these changes and I'll give it another look! =)

**Comment by hemao** [comment]
Hi @allison-johnson, I made the corrections. Please review.

**Comment by allison-johnson** [comment]
@hemao , this branch has merge conflicts. Can you please resolve them and then I'll take a look at the code? Thanks!

**Comment by hemao** [comment]
@allison-johnson , I think corrected the issue with conflicts now. Please review.

**Pull request merged**
