### PR TITLE
added testimonial component

### PR DESCRIPTION
**Pull request by hemao**

### CODE REVIEW

**Comment by allison-johnson** [comment]
@hemao , this is a great start! Just a couple of fixes before we merge this into develop:
- On the mock up, the testimonial component doesn't actually include an image. If it is supposed to, can you please adjust that on the mock up?

Assuming that the component _should_ include an image:
- Please give your stories more descriptive names (i.e., instead of just 1 and 2). Perhaps something like `ImageLeft` and `ImageRight`?
- As per the mock up, the images should be taller than the text boxes, and the text boxes should be centered vertically relative to the images.

Let me know when you've committed these changes and I'll take another look!

**Comment by hemao** [comment]
Hi @allison-johnson, I made changes based on feedback. Please review.

**Comment by clarknoah** [comment]
@hemao this looks really good, just a few things: 

1. Right now your dimensions are hard coded in CSS, this is why when the page resizes, the text clips out of the blue bordered container, please correct this. It should be responsive. I'd think about using some `min-height` CSS along with some percentages. Totally up to you how you do it, but just make it responsive! Thanks!

**Comment by hemao** [comment]
Hi @clarknoah, I removed the hardcoded style. Please review

**Comment by clarknoah** [comment]
@hemao looks great!

**Pull request merged**
