### PR TITLE
Aboutus

### PR DESCRIPTION
**Pull request by ram-bor**
As far as functionality, the arrows on the 'Our Members' section should work once Jennifer pushes up her changes, then I will pull and merge the changes. 

I would like some visual and responsiveness feedback on the page itself so I do not encounter any blockers.

Thanks!

### CODE REVIEW

**Comment by allison-johnson** [comment]
@ram-bor , good start! Here is some section-by-section initial feedback on the page:

- **We are SWB**: The photo should be smaller and vertically centered relative to the text. Also, the blue horizontal line underneath does not extend all the way across the screen when the window is at 100% (this is likely because of the image size).

- **How We Started**: Looks good!

- **Our Members**: Cards should be centered horizontally on the page. In terms of responsiveness, the cards should scale down in size as the window gets smaller (to a point).

- **Objectives**: The words "SWB charter" should have a faint gray underline (and be linked to their charter?)

- **Funding Facts**: There is a bit too much space above the header (below the blue line). The words "Volunteer code of conduct and Privacy Policy" should have a faint gray underline (and be linked to something). The responsiveness of this section is really nice!

- **SWB and ASA**: Looks good!

**Comment by allison-johnson** [comment]
@ram-bor this is looking great! Just a few more fixes:

- **We Are SWB**: In terms of responsiveness, when the window shrinks, at a certain point we'd just want the text to be _underneath_ the picture (rather than beside it).

- **Our Members**: The responsiveness is great! One thing: I believe `IconDownArrow` takes in a prop of a callback function, which should tell the arrow what to do when it is clicked. In this case, we want the remainder of the text to show. Can you try to make that happen?

- **Objectives and Funding Facts**: These are just missing the links. We can merge the branch without them, but can you please **open up an issue to add links to About Us** (specifying which links need to be added) so that we can make sure to come back to that?

Let me know when you've pushed up the changes and I'll take another look! =)

**Comment by ram-bor** [comment]
I made some changes to the MemberCard.js and .css due to the arrows showing up on each member card. Easy fix. Also, I got the image to show up in the first section above the text. Hooray!

**Comment by ram-bor** [comment]
Now for the links, I do not see any pages that would prompt the Policy page or the Charter page so I'm confused as to what they will be or what the client intends to have them link to...I have added empty strings to the href in the code though.

**Comment by ram-bor** [comment]
But let me know if you would like me to go ahead and create an issue for them.

**Comment by allison-johnson** [comment]
@ram-bor , thanks for making those changes! Here are a couple of things I noticed that need to be fixed:

- **We are SWB**: The header doesn't show up when the screen is at 100%. In fact, it only shows once the width of the window has shrunk significantly.

- **How We Started**: The header is a bit too close to the blue line.

- **Our Members**: I can't remember if this responsiveness was working before, but the cards should get smaller and begin to stack vertically as the window size shrinks. Also, Cathy Furlong's card needs an arrow.

- **Using Global Variables**: Instead of hard coding colors into your CSS rules (happens a few times), please use the global variables defined in `index.css`

Let me know when you've pushed up the changes and I'll take another look!

**Comment by allison-johnson** [comment]
@ram-bor , this is getting really close! Can you please try to fix the following issue: when the screen gets small, the images in the **Our Members** section stay a bit too large and are no longer centered horizontally.

Thanks!

**Comment by ram-bor** [comment]
I apologize but that is the best I could do in terms of responsiveness. I could not control much through the 'AboutUsPage.css'  due to some styling formatting on the MemberCard component css. I tried to not do much on that component due to risk of going back and changing things since I did not work on it. The images should be smaller and the text does align when the user shrinks it down to a mobile device size.

**Comment by ram-bor** [comment]
I also successfully added missing links and is working fine.

**Pull request merged**
