### PR TITLE
Feature video ak Issue#50

### PR DESCRIPTION
**Pull request by Afkelly14**

### CODE REVIEW

**Comment by allison-johnson** [comment]
@Afkelly14 , please adjust the CSS to make the videos more responsive (i.e., instead of hard-coding pixel values for width and height, use percentages so that they scale appropriately when the window size changes). 

Let me know when you've pushed these changes and I'll have another look! :)

**Comment by allison-johnson** [comment]
@Afkelly14 , although you changed the `width` and `height` to percentages in the CSS file, the videos are still not responsive. (You'll see this if you `run storybook` and adjust the window size.). I think this has to do with (1) the fact that your `div` has `className`s of _both_ `Video-large` and `Video-small`, and (2) the fact that when you create your stories, you are hard-coding pixel values to pass in as the `width` and `height`.

Let me know when you've pushed up your revised code and I'll take another look!

**Comment by clarknoah** [comment]
@Afkelly14 can you make it so that the user doesn't have to input a pre-determined width/height?  Have the width simply be 100% and have the height be set to `auto`

**Comment by clarknoah** [comment]
Also, please remove any code that is unused

**Pull request merged**
