### PR TITLE
Project Model and Service Model for backend

### PR DESCRIPTION
**Pull request by AnthonyMaddox**
We set up swb app and install dependencies. We created a model for project and a model for service with a foreign key that links services to a project.

### CODE REVIEW

**Comment by allison-johnson** [comment]
@AnthonyMaddox , great start on the database models! The one major issue to tackle right now is the following: you have `Project` and `Service` set up with a "belongs-to" relationship; i.e., a service "belongs-to" a project (via its `project_id` foreign key). The problem is that a service can "belong to" _many_ projects. Similarly, a project can have _many_ services associated with it. For this reason, we would call the relationship between `Project` and `Service` a many-to-many relationship.

Rather than using a foreign key column, a many-to-many relationship requires something called a **join table**. Basically, each record in this particular join table (probably called something like `ProjectServices`) would have both `project_id` and a `service_id` and would indicate all the _pairs_ of associated projects/services.

See Django documentation on setting up many-to-many relationships [here](https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/). 

Let me know when you've pushed up these changes and I'll take another look! =)

**Comment by AnthonyMaddox** [comment]
Added ManyToMany relationship between service and project models and tested in iPython. I couldn't quite tell how it was working in the admin browser window until iPython. Each project has a list of all the services created but only the highlighted ones are assigned to that project. Let me know what you think!

**Comment by allison-johnson** [comment]
@AnthonyMaddox , this is looking much better! Great job implementing that many-to-many relationship :)

I'd say a good next step would be to **seed the database** with projects and services. You'll also want to add uniqueness validators to the service (i.e., the `services` table can't have two records with the same title). You may be able to seed the tables just by making a migration and adding the records you want to add.

Once you've seeded the data, you can check and see if the many-to-many relationship is still working and making sense!

Let me know if you have any questions and I'll look again once you've pushed up the changes!

**Comment by allison-johnson** [comment]
@AnthonyMaddox , as we discussed, please
- Include instructions for dropping `swb` database and user if it already exists
- Change seeding so that primary keys (id's) are assigned automatically

**Comment by allison-johnson** [comment]
@AnthonyMaddox , when I run `python3 manage.py makemigrations` there is a `Conflicting Migrations` error ... please fix and push up the changes. Thanks!

**Comment by AnthonyMaddox** [comment]
taking a look now

**Pull request merged**
