### PR TITLE
HomePage #48

### PR DESCRIPTION
**Pull request by jscott4720**

### CODE REVIEW

**Comment by allison-johnson** [comment]
@jscott4720 , great start with this! A few small things to take care of before we merge this into develop:

- The header ("We Use Data For Good") should be aligned with the text below it. It should also be white. 
- All of the text/buttons on your `banner` div should fit in the left half and top two-thirds of the image (see mock up).
- Change the width of the text box in the `probono` class (it's too wide right now)
- There's a bit too much space before/after the "What We Do" header. Also, make sure the spacing around all headers is consistent ("What We Do", "Who We Are", etc.)
- Description under "Who We Are" is too wide; it should match width of other descriptions.
- Remove the last blue horizontal line (that will be part of the `Footer` component)

Let me know when you've pushed these changes and I'll take another look! (Also, don't forget to pull from develop as there may have been some changes that affect your component as well)

**Comment by allison-johnson** [comment]
@jscott4720 , this is looking great! The last thing I noticed is that when the window is resized (horizontally), the blog cards overlap in a very unattractive way (as opposed to the What We Do cards, which remain nicely spaced). Please fix that and let me know when you've pushed up the code!

**Comment by jscott4720** [comment]
@allison-johnson added that spacing

**Comment by jscott4720** [comment]
@allison-johnson if you happen to be checking this right now and it is good to merge could you hold off for a little, I forgot to add links

**Comment by jscott4720** [comment]
@allison-johnson added the links

**Comment by allison-johnson** [comment]
@jscott4720 , this is looking great! There is one last thing to take care of in terms of responsiveness. Although all of the different cards do maintain their spacing when the screen shrinks, at some point when the screen is small enough you will want to the cards to **stack on top of each other** since they are not all visible horizontally. Please test to make sure you do this for all sets of cards on the home page.

Almost there, I promise!!

**Comment by jscott4720** [comment]
@allison-johnson hopefully this is good

**Comment by clarknoah** [comment]
This is looking great, there are a couple things that still need to be responsive, see below. Alot of them aren't centering in the middle. This may require fixing the sub components of the Home page to rectify. 

I know that the testimonial component needs improved for this to work properly. I'll create that issue, see if you can't resolve the other issues internally. If the issues for the other parts needs corrected at the component level, please create issues for them with the detail requirements so that they center on mobile displays.

Screen Shot 2020-08-28 at 3 34 44 PM
Screen Shot 2020-08-28 at 3 34 23 PM
Screen Shot 2020-08-28 at 3 36 16 PM
Screen Shot 2020-08-28 at 3 36 25 PM

**Pull request merged**
